<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;</TargetFrameworks>

    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StreamingMarkdown.Maui</RootNamespace>
    <AssemblyName>StreamingMarkdown.Maui</AssemblyName>

    <MauiXamlInflator>SourceGen</MauiXamlInflator>

    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>

    <!-- NuGet -->
    <PackageId>StreamingMarkdown.Maui</PackageId>
    <Version>0.1.0</Version>
    <Authors>Shouvik Halder</Authors>
    <Description>
      High-performance incremental Markdown rendering for streaming content in .NET MAUI.
    </Description>
    <PackageTags>maui;markdown;streaming;ai;llm;incremental-rendering</PackageTags>

    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../StreamingMarkdown.Core/StreamingMarkdown.Core.csproj" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

</Project>